# FIXME - in future phase, the runner MUST be in docker group
# so we should not use `sudo docker ....' in below operations...
stages:
  - build
  - test
  - deploy_test
  - deploy_prod

# variables definitions
variables:
  NAMESPACE: "emr-test"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "1"
  CHART_REPO: "staging"
  TEST_REGISTRY: "hub.ops.qspeaker.com/qbrain_test"
  PROD_REGISTRY: "hub.ops.qspeaker.com/qbrain_prod"

build-docker:
  stage: build
  script:
    - echo 'try build the image'
    - sudo docker build -t $TEST_REGISTRY/$CI_PROJECT_NAME:D$CI_PIPELINE_ID .

do-test:
  stage: test
  script:
    - echo 'testing code'

# deploy under test should auto-start
# after mreged to master
deploy-to-testenv:
  stage: deploy_test
  only:
    - master
  script:
    - echo 'try push the docker images...'
    - sudo docker push $TEST_REGISTRY/$CI_PROJECT_NAME:D$CI_PIPELINE_ID
    - echo 'pushed [OK].'
    - helm package --app-version $CI_PIPELINE_ID --version $MAJOR_VERSION.$MINOR_VERSION.$CI_PIPELINE_ID .
    - echo 'Now, try uploading to helm chart repo...'
    - helm s3 push ./$CI_PROJECT_NAME-$MAJOR_VERSION.$MINOR_VERSION.$CI_PIPELINE_ID.tgz $CHART_REPO
    - sudo helm upgrade -i --namespace $NAMESPACE --set replicaCount=2,image.repository=$TEST_REGISTRY/$CI_PROJECT_NAME,image.tag=D$CI_PIPELINE_ID $CI_PROJECT_NAME $CHART_REPO/$CI_PROJECT_NAME

# deploy to product MUST be done manually!
# the deploy executer run in prod-env, with `prod-only' tag!
deploy-to-prodenv:
  stage: deploy_prod
  only:
    - master
  tags:
    - prod-only
  when: manual
  script:
    - echo 'deploy it under prod env'
    - sudo docker pull $TEST_REGISTRY/$CI_PROJECT_NAME:D$CI_PIPELINE_ID
    - sudo docker tag $TEST_REGISTRY/$CI_PROJECT_NAME:D$CI_PIPELINE_ID $PROD_REGISTRY/$CI_PROJECT_NAME:D$CI_PIPELINE_ID
    - sudo docker push $PROD_REGISTRY/$CI_PROJECT_NAME:D$CI_PIPELINE_ID
    - echo 'pushed to prod harbor [OK].'
    - helm upgrade -i --namespace $NAMESPACE --set replicaCount=2,image.repository=$PROD_REGISTRY/$CI_PROJECT_NAME,image.tag=D$CI_PIPELINE_ID $CI_PROJECT_NAME $CHART_REPO/$CI_PROJECT_NAME
