stages:
  - build
  - test
  - deploy

do-build:
  stage: build
  script:
    - echo 'try $CI_COMMIT_REF_NAME and $CI'
    - sudo docker build -t ysx/mynginx:$CI_COMMIT_REF_NAME .

do-test:
  stage: test
  script:
    - echo 'testing code'
do-deploy:
  stage: deploy
  script:
    - echo 'deploy it'
