stages:
  - build
  - test
  - deploy_test
  - deploy_prod

# variables definitions
variables:
  TEST_REGISTRY: "hub.ops.qspeaker.com/qbrain_test/"
  PROD_REGISTRY: "hub.ops.qspeaker.com/qbrain_prod/"

build-docker:
  stage: build
  script:
    - echo 'try build the image'
    - sudo docker build -t ysx/$CI_PROJECT_NAME:D$CI_PIPELINE_ID .

do-test:
  stage: test
  script:
    - echo 'testing code'

# deploy under test should auto-start
# after mreged to master
deploy-to-testenv:
  stage: deploy_test
  only:
    - master
  script:
    - echo 'deploy it'

# deploy to product MUST be done manually!
do-prod:
  stage: deploy_prod
  only:
    - master
  when: manual
  script:
    - echo 'deploy it under prod env'
